// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDI.Enki.Infrastructure.Data;

#nullable disable

namespace SDI.Enki.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260425153719_WellsUnderJobs")]
    partial class WellsUnderJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommentGradient", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int");

                    b.Property<int>("GradientsId")
                        .HasColumnType("int");

                    b.HasKey("CommentsId", "GradientsId");

                    b.HasIndex("GradientsId");

                    b.ToTable("GradientComment", (string)null);
                });

            modelBuilder.Entity("CommentPassive", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int");

                    b.Property<int>("PassivesId")
                        .HasColumnType("int");

                    b.HasKey("CommentsId", "PassivesId");

                    b.HasIndex("PassivesId");

                    b.ToTable("PassiveComment", (string)null);
                });

            modelBuilder.Entity("CommentRotary", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int");

                    b.Property<int>("RotariesId")
                        .HasColumnType("int");

                    b.HasKey("CommentsId", "RotariesId");

                    b.HasIndex("RotariesId");

                    b.ToTable("RotaryComment", (string)null);
                });

            modelBuilder.Entity("GradientModelRun", b =>
                {
                    b.Property<int>("GradientModelsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GradientModelsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("GradientModelRun", (string)null);
                });

            modelBuilder.Entity("OperatorRun", b =>
                {
                    b.Property<int>("OperatorsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OperatorsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("RunOperator", (string)null);
                });

            modelBuilder.Entity("RotaryModelRun", b =>
                {
                    b.Property<int>("RotaryModelsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RotaryModelsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("RotaryModelRun", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Comments.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("Identity")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WellName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("Status");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("JobUser");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.ReferencedJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ReferencedJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReferencedTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReferencedTenantId", "ReferencedJobId");

                    b.ToTable("ReferencedJob");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bx")
                        .HasColumnType("float");

                    b.Property<double>("By")
                        .HasColumnType("float");

                    b.Property<double>("Bz")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Gx")
                        .HasColumnType("float");

                    b.Property<double>("Gy")
                        .HasColumnType("float");

                    b.Property<double>("Gz")
                        .HasColumnType("float");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.HasIndex("LoggingId", "Depth");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LogTimeDepth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<int>("LoggingTimeDepthId")
                        .HasColumnType("int");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LoggingTimeDepthId");

                    b.ToTable("LogTimeDepth", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.Logging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalibrationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FileTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GradientRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogSettingId")
                        .HasColumnType("int");

                    b.Property<int>("MagneticId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PassiveRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RotaryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.HasIndex("GradientRunId");

                    b.HasIndex("LogSettingId");

                    b.HasIndex("MagneticId");

                    b.HasIndex("PassiveRunId");

                    b.HasIndex("RotaryRunId");

                    b.ToTable("Logging", null, t =>
                        {
                            t.HasCheckConstraint("CK_Loggings_ExactlyOneRun", "(CASE WHEN [GradientRunId] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [RotaryRunId]   IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [PassiveRunId]  IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingEfd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bx")
                        .HasColumnType("float");

                    b.Property<double>("By")
                        .HasColumnType("float");

                    b.Property<double>("Bz")
                        .HasColumnType("float");

                    b.Property<double>("Gx")
                        .HasColumnType("float");

                    b.Property<double>("Gy")
                        .HasColumnType("float");

                    b.Property<double>("Gz")
                        .HasColumnType("float");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.Property<double>("MeasuredDepth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.ToTable("LoggingEfd", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.ToTable("LoggingFile", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingProcessing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLodestone")
                        .HasColumnType("bit");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId")
                        .IsUnique();

                    b.ToTable("LoggingProcessing", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AverageOverInterval")
                        .HasColumnType("bit");

                    b.Property<double>("DepthOffset")
                        .HasColumnType("float");

                    b.Property<double>("DepthOutputInterval")
                        .HasColumnType("float");

                    b.Property<bool>("OutputEfd")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessOneDirection")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseGsSign")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowQualifyPlots")
                        .HasColumnType("bit");

                    b.Property<bool>("TrackDepth")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LoggingSetting", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingTimeDepth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Closed")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("EndDepth")
                        .HasColumnType("float");

                    b.Property<double>("EndTime")
                        .HasColumnType("float");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("StartDepth")
                        .HasColumnType("float");

                    b.Property<double>("StartTime")
                        .HasColumnType("float");

                    b.Property<double>("TimeInterval")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.ToTable("LoggingTimeDepth", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.PassiveLoggingProcessing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLodestone")
                        .HasColumnType("bit");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId")
                        .IsUnique();

                    b.ToTable("PassiveLoggingProcessing", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.RotaryProcessing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoResend")
                        .HasColumnType("bit");

                    b.Property<double>("Current")
                        .HasColumnType("float");

                    b.Property<double>("HighCutoff")
                        .HasColumnType("float");

                    b.Property<bool>("IsLodestone")
                        .HasColumnType("bit");

                    b.Property<int>("LoggingId")
                        .HasColumnType("int");

                    b.Property<double>("LowCutoff")
                        .HasColumnType("float");

                    b.Property<int>("SurveyMagUsed")
                        .HasColumnType("int");

                    b.Property<bool>("Units")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId")
                        .IsUnique();

                    b.ToTable("RotaryProcessing", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.GradientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InjectionWellId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TargetWellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InjectionWellId");

                    b.HasIndex("TargetWellId");

                    b.ToTable("GradientModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.RotaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InjectionWellId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TargetWellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InjectionWellId");

                    b.HasIndex("TargetWellId");

                    b.ToTable("RotaryModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.SavedGradientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GradientModelId")
                        .HasColumnType("int");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SaveType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.HasIndex("GradientModelId");

                    b.ToTable("SavedGradientModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Operators.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BridleLength")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("CurrentInjection")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("EndDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("StartDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Type");

                    b.ToTable("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ActiveField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CosX")
                        .HasColumnType("float");

                    b.Property<double>("CosY")
                        .HasColumnType("float");

                    b.Property<double>("CosZ")
                        .HasColumnType("float");

                    b.Property<double>("Field")
                        .HasColumnType("float");

                    b.Property<int>("Mag")
                        .HasColumnType("int");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<double>("SinX")
                        .HasColumnType("float");

                    b.Property<double>("SinY")
                        .HasColumnType("float");

                    b.Property<double>("SinZ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("ActiveField");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalibrationString")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "CalibrationString")
                        .IsUnique();

                    b.ToTable("Calibration");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Gradient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Frame")
                        .HasColumnType("int");

                    b.Property<double?>("Frequency")
                        .HasColumnType("float");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Order");

                    b.ToTable("Gradient");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GradientFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("GradientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GradientId");

                    b.ToTable("GradientFile");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GradientSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AziToTarget")
                        .HasColumnType("float");

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<int>("GradientId")
                        .HasColumnType("int");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("MdToTarget")
                        .HasColumnType("float");

                    b.Property<double>("MeasuredDepth")
                        .HasColumnType("float");

                    b.Property<bool>("SignFlipped")
                        .HasColumnType("bit");

                    b.Property<double>("TfToTarget")
                        .HasColumnType("float");

                    b.Property<double>("Toolface")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GradientId");

                    b.ToTable("GradientSolution");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GyroShot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccelerometerQuality")
                        .HasColumnType("int");

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("DeltaBias")
                        .HasColumnType("float");

                    b.Property<double>("DeltaDrift")
                        .HasColumnType("float");

                    b.Property<double>("EarthRateHorizontal")
                        .HasColumnType("float");

                    b.Property<int>("Gain")
                        .HasColumnType("int");

                    b.Property<double>("GyroToolface")
                        .HasColumnType("float");

                    b.Property<double>("HighSideToolface")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<double>("Noise")
                        .HasColumnType("float");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<int>("StartTimestamp")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Synch")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<int>("Timestamp")
                        .HasColumnType("int");

                    b.Property<double?>("ToolfaceOffset")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("GyroShot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Magnetics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BTotal")
                        .HasColumnType("float");

                    b.Property<double>("Declination")
                        .HasColumnType("float");

                    b.Property<double>("Dip")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BTotal", "Dip", "Declination")
                        .IsUnique();

                    b.ToTable("Magnetics");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Passive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AziToTarget")
                        .HasColumnType("float");

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("MdToTarget")
                        .HasColumnType("float");

                    b.Property<double>("MeasuredDepth")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TfToTarget")
                        .HasColumnType("float");

                    b.Property<double>("Toolface")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Order");

                    b.ToTable("Passive");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.PassiveFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PassiveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PassiveId");

                    b.ToTable("PassiveFile");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Rotary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Frame")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Order");

                    b.ToTable("Rotary");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.RotaryFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RotaryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RotaryId");

                    b.ToTable("RotaryFile");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.RotarySolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AxialToSensor")
                        .HasColumnType("float");

                    b.Property<double>("DistanceAtPassBy")
                        .HasColumnType("float");

                    b.Property<double>("DistanceToPassBy")
                        .HasColumnType("float");

                    b.Property<double>("EastToSensor")
                        .HasColumnType("float");

                    b.Property<double>("HighSideToSensor")
                        .HasColumnType("float");

                    b.Property<double>("NorthToSensor")
                        .HasColumnType("float");

                    b.Property<double>("PassByApproachAngle")
                        .HasColumnType("float");

                    b.Property<double>("PassByTotalDistance")
                        .HasColumnType("float");

                    b.Property<double>("RightSideToSensor")
                        .HasColumnType("float");

                    b.Property<int>("RotaryId")
                        .HasColumnType("int");

                    b.Property<double>("RotorAzimuth")
                        .HasColumnType("float");

                    b.Property<double>("RotorInclination")
                        .HasColumnType("float");

                    b.Property<double>("RotorMeasuredDepth")
                        .HasColumnType("float");

                    b.Property<int>("RotorMoment")
                        .HasColumnType("int");

                    b.Property<double>("SensorAzimuth")
                        .HasColumnType("float");

                    b.Property<double>("SensorInclination")
                        .HasColumnType("float");

                    b.Property<int>("SensorLobe")
                        .HasColumnType("int");

                    b.Property<double>("SensorMagnetometer")
                        .HasColumnType("float");

                    b.Property<double>("SensorMeasuredDepth")
                        .HasColumnType("float");

                    b.Property<double>("SensorShieldMatrixXY")
                        .HasColumnType("float");

                    b.Property<double>("SensorShieldMatrixZ")
                        .HasColumnType("float");

                    b.Property<double>("SensorToolface")
                        .HasColumnType("float");

                    b.Property<double>("VerticalToSensor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RotaryId");

                    b.ToTable("RotarySolution");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bandwidth")
                        .HasColumnType("float");

                    b.Property<int?>("CalibrationsId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FileTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Frequency")
                        .HasColumnType("float");

                    b.Property<int?>("GradientId")
                        .HasColumnType("int");

                    b.Property<int?>("MagneticsId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMags")
                        .HasColumnType("int");

                    b.Property<int?>("RotaryId")
                        .HasColumnType("int");

                    b.Property<int?>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int>("SampleFrequency")
                        .HasColumnType("int");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ShotTime")
                        .HasColumnType("int");

                    b.Property<int>("TimeEnd")
                        .HasColumnType("int");

                    b.Property<int>("TimeStart")
                        .HasColumnType("int");

                    b.Property<int>("ToolUptime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationsId");

                    b.HasIndex("GradientId");

                    b.HasIndex("MagneticsId");

                    b.HasIndex("RotaryId");

                    b.ToTable("Shot", t =>
                        {
                            t.HasCheckConstraint("CK_Shots_ExactlyOneParent", "([GradientId] IS NULL AND [RotaryId] IS NOT NULL) OR ([GradientId] IS NOT NULL AND [RotaryId] IS NULL)");
                        });
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ToolSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("BTotal")
                        .HasColumnType("float");

                    b.Property<double>("Bx")
                        .HasColumnType("float");

                    b.Property<double>("By")
                        .HasColumnType("float");

                    b.Property<double>("Bz")
                        .HasColumnType("float");

                    b.Property<double?>("Current")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Dip")
                        .HasColumnType("float");

                    b.Property<double>("GTotal")
                        .HasColumnType("float");

                    b.Property<double>("GravityToolface")
                        .HasColumnType("float");

                    b.Property<double>("Gx")
                        .HasColumnType("float");

                    b.Property<double>("Gy")
                        .HasColumnType("float");

                    b.Property<double>("Gz")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("Mag1Ab")
                        .HasColumnType("float");

                    b.Property<double>("Mag2Ab")
                        .HasColumnType("float");

                    b.Property<double>("Mag3Ab")
                        .HasColumnType("float");

                    b.Property<double>("Mag4Ab")
                        .HasColumnType("float");

                    b.Property<double>("MagneticToolface")
                        .HasColumnType("float");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("ToolSurvey");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.CommonMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("FromVertical")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("ToVertical")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("CommonMeasure");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FromVertical")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Resistance")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("ToVertical")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Build")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("DoglegSeverity")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("SubSea")
                        .HasColumnType("float");

                    b.Property<double>("Turn")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("VerticalDepth")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Depth");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("SubSeaReference")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("VerticalReference")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSectionDirection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("TieOn");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Tubular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<double>("FromMeasured")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("ToMeasured")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Order");

                    b.ToTable("Tubular");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Well");
                });

            modelBuilder.Entity("CommentGradient", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Comments.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", null)
                        .WithMany()
                        .HasForeignKey("GradientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommentPassive", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Comments.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Passive", null)
                        .WithMany()
                        .HasForeignKey("PassivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommentRotary", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Comments.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", null)
                        .WithMany()
                        .HasForeignKey("RotariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradientModelRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Models.GradientModel", null)
                        .WithMany()
                        .HasForeignKey("GradientModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OperatorRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Operators.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotaryModelRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Models.RotaryModel", null)
                        .WithMany()
                        .HasForeignKey("RotaryModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.ReferencedJob", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("References")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.Log", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithMany("Logs")
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LogTimeDepth", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.LoggingTimeDepth", "LoggingTimeDepth")
                        .WithMany("Samples")
                        .HasForeignKey("LoggingTimeDepthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoggingTimeDepth");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.Logging", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Calibration", "Calibration")
                        .WithMany()
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "GradientRun")
                        .WithMany()
                        .HasForeignKey("GradientRunId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.LoggingSetting", "LoggingSetting")
                        .WithMany()
                        .HasForeignKey("LogSettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Magnetics", "Magnetics")
                        .WithMany()
                        .HasForeignKey("MagneticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "PassiveRun")
                        .WithMany()
                        .HasForeignKey("PassiveRunId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "RotaryRun")
                        .WithMany()
                        .HasForeignKey("RotaryRunId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Calibration");

                    b.Navigation("GradientRun");

                    b.Navigation("LoggingSetting");

                    b.Navigation("Magnetics");

                    b.Navigation("PassiveRun");

                    b.Navigation("RotaryRun");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingEfd", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithMany("EfdSamples")
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingFile", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithMany("Files")
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingProcessing", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithOne("LoggingProcessing")
                        .HasForeignKey("SDI.Enki.Core.TenantDb.Logging.LoggingProcessing", "LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingTimeDepth", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithMany("TimeDepths")
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.PassiveLoggingProcessing", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithOne("PassiveLoggingProcessing")
                        .HasForeignKey("SDI.Enki.Core.TenantDb.Logging.PassiveLoggingProcessing", "LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.RotaryProcessing", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logging.Logging", "Logging")
                        .WithOne("RotaryProcessing")
                        .HasForeignKey("SDI.Enki.Core.TenantDb.Logging.RotaryProcessing", "LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.GradientModel", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "InjectionWell")
                        .WithMany()
                        .HasForeignKey("InjectionWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "TargetWell")
                        .WithMany()
                        .HasForeignKey("TargetWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InjectionWell");

                    b.Navigation("TargetWell");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.RotaryModel", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "InjectionWell")
                        .WithMany()
                        .HasForeignKey("InjectionWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "TargetWell")
                        .WithMany()
                        .HasForeignKey("TargetWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InjectionWell");

                    b.Navigation("TargetWell");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.SavedGradientModel", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Models.GradientModel", "GradientModel")
                        .WithMany("SavedSnapshots")
                        .HasForeignKey("GradientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradientModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Runs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ActiveField", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("ActiveFields")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Gradient", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Gradients")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GradientFile", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", "Gradient")
                        .WithMany("Files")
                        .HasForeignKey("GradientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gradient");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GradientSolution", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", "Gradient")
                        .WithMany("Solutions")
                        .HasForeignKey("GradientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gradient");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GyroShot", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("GyroShots")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Passive", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Passives")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.PassiveFile", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Passive", "Passive")
                        .WithMany("Files")
                        .HasForeignKey("PassiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passive");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Rotary", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Rotaries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.RotaryFile", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", "Rotary")
                        .WithMany("Files")
                        .HasForeignKey("RotaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rotary");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.RotarySolution", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", "Rotary")
                        .WithMany("Solutions")
                        .HasForeignKey("RotaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rotary");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Calibration", "Calibration")
                        .WithMany()
                        .HasForeignKey("CalibrationsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", "Gradient")
                        .WithMany("Shots")
                        .HasForeignKey("GradientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Magnetics", "Magnetics")
                        .WithMany()
                        .HasForeignKey("MagneticsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", "Rotary")
                        .WithMany("Shots")
                        .HasForeignKey("RotaryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Calibration");

                    b.Navigation("Gradient");

                    b.Navigation("Magnetics");

                    b.Navigation("Rotary");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ToolSurvey", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("ToolSurveys")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.CommonMeasure", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("CommonMeasures")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Formation", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Formations")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Surveys")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("TieOns")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Tubular", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Tubulars")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Wells")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Runs");

                    b.Navigation("Users");

                    b.Navigation("Wells");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.Logging", b =>
                {
                    b.Navigation("EfdSamples");

                    b.Navigation("Files");

                    b.Navigation("LoggingProcessing");

                    b.Navigation("Logs");

                    b.Navigation("PassiveLoggingProcessing");

                    b.Navigation("RotaryProcessing");

                    b.Navigation("TimeDepths");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logging.LoggingTimeDepth", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.GradientModel", b =>
                {
                    b.Navigation("SavedSnapshots");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Navigation("Gradients");

                    b.Navigation("Passives");

                    b.Navigation("Rotaries");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Gradient", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");

                    b.Navigation("Shots");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Passive", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Rotary", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");

                    b.Navigation("Shots");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.Navigation("ActiveFields");

                    b.Navigation("GyroShots");

                    b.Navigation("ToolSurveys");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Navigation("CommonMeasures");

                    b.Navigation("Formations");

                    b.Navigation("Surveys");

                    b.Navigation("TieOns");

                    b.Navigation("Tubulars");
                });
#pragma warning restore 612, 618
        }
    }
}
