// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDI.Enki.Infrastructure.Data;

#nullable disable

namespace SDI.Enki.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260430215917_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradientModelRun", b =>
                {
                    b.Property<int>("GradientModelsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GradientModelsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("GradientModelRun", (string)null);
                });

            modelBuilder.Entity("OperatorRun", b =>
                {
                    b.Property<int>("OperatorsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OperatorsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("RunOperator", (string)null);
                });

            modelBuilder.Entity("RotaryModelRun", b =>
                {
                    b.Property<int>("RotaryModelsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RotaryModelsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("RotaryModelRun", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Comments.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("Identity")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WellName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("Status");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("JobUser");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.ReferencedJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ReferencedJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReferencedTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReferencedTenantId", "ReferencedJobId");

                    b.ToTable("ReferencedJob");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logs.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Binary")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BinaryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("BinaryUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CalibrationId")
                        .HasColumnType("int");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ConfigUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("FileTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.HasIndex("RunId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logs.LogResultFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogResultFile");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.GradientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InjectionWellId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TargetWellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InjectionWellId");

                    b.HasIndex("TargetWellId");

                    b.ToTable("GradientModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.RotaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InjectionWellId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TargetWellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InjectionWellId");

                    b.HasIndex("TargetWellId");

                    b.ToTable("RotaryModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.SavedGradientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GradientModelId")
                        .HasColumnType("int");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SaveType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.HasIndex("GradientModelId");

                    b.ToTable("SavedGradientModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Operators.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("BridleLength")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("CurrentInjection")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("EndDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MagneticsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PassiveBinary")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PassiveBinaryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("PassiveBinaryUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PassiveConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PassiveConfigUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PassiveResultComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PassiveResultError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassiveResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassiveResultMardukVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassiveResultStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SnapshotCalibrationId")
                        .HasColumnType("int");

                    b.Property<double>("StartDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("ToolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("JobId");

                    b.HasIndex("MagneticsId");

                    b.HasIndex("PassiveResultStatus");

                    b.HasIndex("SnapshotCalibrationId");

                    b.HasIndex("ToolId");

                    b.HasIndex("Type");

                    b.ToTable("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalibratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CalibrationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsNominal")
                        .HasColumnType("bit");

                    b.Property<int>("MagnetometerCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MasterCalibrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MasterCalibrationId")
                        .IsUnique();

                    b.HasIndex("ToolId");

                    b.ToTable("Calibration");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Magnetics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BTotal")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Declination")
                        .HasColumnType("float");

                    b.Property<double>("Dip")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId")
                        .IsUnique()
                        .HasFilter("[WellId] IS NOT NULL");

                    b.ToTable("Magnetics");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Binary")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BinaryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("BinaryUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CalibrationId")
                        .HasColumnType("int");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ConfigUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("FileTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("GyroBinary")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("GyroBinaryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("GyroBinaryUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GyroConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("GyroConfigUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("GyroResultComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GyroResultError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GyroResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GyroResultMardukVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GyroResultStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ResultComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResultError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultMardukVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.HasIndex("GyroResultStatus");

                    b.HasIndex("ResultStatus");

                    b.HasIndex("RunId");

                    b.ToTable("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.CommonMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("FromMeasured")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("ToMeasured")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("CommonMeasure");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FromMeasured")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Resistance")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("ToMeasured")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Build")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("DoglegSeverity")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("SubSea")
                        .HasColumnType("float");

                    b.Property<double>("Turn")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("VerticalDepth")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Depth");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("SubSeaReference")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("VerticalReference")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSectionDirection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("TieOn");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Tubular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<double>("FromMeasured")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("ToMeasured")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Order");

                    b.ToTable("Tubular");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("JobId");

                    b.ToTable("Well");
                });

            modelBuilder.Entity("GradientModelRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Models.GradientModel", null)
                        .WithMany()
                        .HasForeignKey("GradientModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OperatorRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Operators.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotaryModelRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Models.RotaryModel", null)
                        .WithMany()
                        .HasForeignKey("RotaryModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Comments.Comment", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("Comments")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.ReferencedJob", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("References")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logs.Log", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Calibration", "Calibration")
                        .WithMany()
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Logs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calibration");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logs.LogResultFile", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Logs.Log", "Log")
                        .WithMany("ResultFiles")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.GradientModel", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "InjectionWell")
                        .WithMany()
                        .HasForeignKey("InjectionWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "TargetWell")
                        .WithMany()
                        .HasForeignKey("TargetWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InjectionWell");

                    b.Navigation("TargetWell");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.RotaryModel", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "InjectionWell")
                        .WithMany()
                        .HasForeignKey("InjectionWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "TargetWell")
                        .WithMany()
                        .HasForeignKey("TargetWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InjectionWell");

                    b.Navigation("TargetWell");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.SavedGradientModel", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Models.GradientModel", "GradientModel")
                        .WithMany("SavedSnapshots")
                        .HasForeignKey("GradientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradientModel");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Runs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Magnetics", "Magnetics")
                        .WithMany()
                        .HasForeignKey("MagneticsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Calibration", "SnapshotCalibration")
                        .WithMany()
                        .HasForeignKey("SnapshotCalibrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Job");

                    b.Navigation("Magnetics");

                    b.Navigation("SnapshotCalibration");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Magnetics", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithOne("Magnetics")
                        .HasForeignKey("SDI.Enki.Core.TenantDb.Shots.Magnetics", "WellId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Calibration", "Calibration")
                        .WithMany()
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Shots")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calibration");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.CommonMeasure", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("CommonMeasures")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Formation", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Formations")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Surveys")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("TieOns")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Tubular", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Tubulars")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Wells")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Runs");

                    b.Navigation("Users");

                    b.Navigation("Wells");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Logs.Log", b =>
                {
                    b.Navigation("ResultFiles");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Models.GradientModel", b =>
                {
                    b.Navigation("SavedSnapshots");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Shots");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Navigation("CommonMeasures");

                    b.Navigation("Formations");

                    b.Navigation("Magnetics");

                    b.Navigation("Surveys");

                    b.Navigation("TieOns");

                    b.Navigation("Tubulars");
                });
#pragma warning restore 612, 618
        }
    }
}
