// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDI.Enki.Infrastructure.Data;

#nullable disable

namespace SDI.Enki.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260424023420_AddShotsAndUnifiedShotChildren")]
    partial class AddShotsAndUnifiedShotChildren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperatorRun", b =>
                {
                    b.Property<int>("OperatorsId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OperatorsId", "RunsId");

                    b.HasIndex("RunsId");

                    b.ToTable("RunOperator", (string)null);
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EntityCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.Property<string>("WellName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("JobUsers");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Operators.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BridleLength")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentInjection")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("EndDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EntityCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("StartDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Type");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ActiveField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CosX")
                        .HasColumnType("float");

                    b.Property<double>("CosY")
                        .HasColumnType("float");

                    b.Property<double>("CosZ")
                        .HasColumnType("float");

                    b.Property<double>("Field")
                        .HasColumnType("float");

                    b.Property<int>("Mag")
                        .HasColumnType("int");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<double>("SinX")
                        .HasColumnType("float");

                    b.Property<double>("SinY")
                        .HasColumnType("float");

                    b.Property<double>("SinZ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("ActiveFields");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalibrationString")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "CalibrationString")
                        .IsUnique();

                    b.ToTable("Calibrations");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Gradient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Frame")
                        .HasColumnType("int");

                    b.Property<double?>("Frequency")
                        .HasColumnType("float");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Order");

                    b.ToTable("Gradients");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GyroShot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccelerometerQuality")
                        .HasColumnType("int");

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("DeltaBias")
                        .HasColumnType("float");

                    b.Property<double>("DeltaDrift")
                        .HasColumnType("float");

                    b.Property<double>("EarthRateHorizontal")
                        .HasColumnType("float");

                    b.Property<int>("Gain")
                        .HasColumnType("int");

                    b.Property<double>("GyroToolface")
                        .HasColumnType("float");

                    b.Property<double>("HighSideToolface")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<double>("Noise")
                        .HasColumnType("float");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<int>("StartTimestamp")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Synch")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<int>("Timestamp")
                        .HasColumnType("int");

                    b.Property<double?>("ToolfaceOffset")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("GyroShots");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Magnetics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BTotal")
                        .HasColumnType("float");

                    b.Property<double>("Declination")
                        .HasColumnType("float");

                    b.Property<double>("Dip")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BTotal", "Dip", "Declination")
                        .IsUnique();

                    b.ToTable("Magnetics");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Passive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AziToTarget")
                        .HasColumnType("float");

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("MdToTarget")
                        .HasColumnType("float");

                    b.Property<double>("MeasuredDepth")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TfToTarget")
                        .HasColumnType("float");

                    b.Property<double>("Toolface")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Order");

                    b.ToTable("Passives");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Rotary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Frame")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Order");

                    b.ToTable("Rotaries");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bandwidth")
                        .HasColumnType("float");

                    b.Property<int?>("CalibrationsId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FileTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Frequency")
                        .HasColumnType("float");

                    b.Property<int?>("GradientId")
                        .HasColumnType("int");

                    b.Property<int?>("MagneticsId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMags")
                        .HasColumnType("int");

                    b.Property<int?>("RotaryId")
                        .HasColumnType("int");

                    b.Property<int?>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int>("SampleFrequency")
                        .HasColumnType("int");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ShotTime")
                        .HasColumnType("int");

                    b.Property<int>("TimeEnd")
                        .HasColumnType("int");

                    b.Property<int>("TimeStart")
                        .HasColumnType("int");

                    b.Property<int>("ToolUptime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationsId");

                    b.HasIndex("GradientId");

                    b.HasIndex("MagneticsId");

                    b.HasIndex("RotaryId");

                    b.ToTable("Shots", t =>
                        {
                            t.HasCheckConstraint("CK_Shots_ExactlyOneParent", "([GradientId] IS NULL AND [RotaryId] IS NOT NULL) OR ([GradientId] IS NOT NULL AND [RotaryId] IS NULL)");
                        });
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ToolSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("BTotal")
                        .HasColumnType("float");

                    b.Property<double>("Bx")
                        .HasColumnType("float");

                    b.Property<double>("By")
                        .HasColumnType("float");

                    b.Property<double>("Bz")
                        .HasColumnType("float");

                    b.Property<double?>("Current")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Dip")
                        .HasColumnType("float");

                    b.Property<double>("GTotal")
                        .HasColumnType("float");

                    b.Property<double>("GravityToolface")
                        .HasColumnType("float");

                    b.Property<double>("Gx")
                        .HasColumnType("float");

                    b.Property<double>("Gy")
                        .HasColumnType("float");

                    b.Property<double>("Gz")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("Mag1Ab")
                        .HasColumnType("float");

                    b.Property<double>("Mag2Ab")
                        .HasColumnType("float");

                    b.Property<double>("Mag3Ab")
                        .HasColumnType("float");

                    b.Property<double>("Mag4Ab")
                        .HasColumnType("float");

                    b.Property<double>("MagneticToolface")
                        .HasColumnType("float");

                    b.Property<int>("ShotId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.ToTable("ToolSurveys");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.CommonMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FromVertical")
                        .HasColumnType("float");

                    b.Property<double>("ToVertical")
                        .HasColumnType("float");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("CommonMeasures");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FromVertical")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Resistance")
                        .HasColumnType("float");

                    b.Property<double>("ToVertical")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Build")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("DoglegSeverity")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<double>("SubSea")
                        .HasColumnType("float");

                    b.Property<double>("Turn")
                        .HasColumnType("float");

                    b.Property<double>("VerticalDepth")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Depth");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<double>("SubSeaReference")
                        .HasColumnType("float");

                    b.Property<double>("VerticalReference")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSectionDirection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("TieOns");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Tubular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<double>("FromMeasured")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("ToMeasured")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Order");

                    b.ToTable("Tubulars");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wells");
                });

            modelBuilder.Entity("OperatorRun", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Operators.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Runs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ActiveField", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("ActiveFields")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Gradient", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Gradients")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.GyroShot", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("GyroShots")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Passive", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Passives")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Rotary", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Runs.Run", "Run")
                        .WithMany("Rotaries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Calibration", "Calibration")
                        .WithMany()
                        .HasForeignKey("CalibrationsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Gradient", "Gradient")
                        .WithMany("Shots")
                        .HasForeignKey("GradientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Magnetics", "Magnetics")
                        .WithMany()
                        .HasForeignKey("MagneticsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Rotary", "Rotary")
                        .WithMany("Shots")
                        .HasForeignKey("RotaryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Calibration");

                    b.Navigation("Gradient");

                    b.Navigation("Magnetics");

                    b.Navigation("Rotary");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.ToolSurvey", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Shots.Shot", "Shot")
                        .WithMany("ToolSurveys")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.CommonMeasure", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("CommonMeasures")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Formation", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Formations")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Surveys")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("TieOns")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Tubular", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Tubulars")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Navigation("Gradients");

                    b.Navigation("Passives");

                    b.Navigation("Rotaries");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Gradient", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Shots");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Rotary", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Shots");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Shots.Shot", b =>
                {
                    b.Navigation("ActiveFields");

                    b.Navigation("GyroShots");

                    b.Navigation("ToolSurveys");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Navigation("CommonMeasures");

                    b.Navigation("Formations");

                    b.Navigation("Surveys");

                    b.Navigation("TieOns");

                    b.Navigation("Tubulars");
                });
#pragma warning restore 612, 618
        }
    }
}
