// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDI.Enki.Infrastructure.Data;

#nullable disable

namespace SDI.Enki.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EntityCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.Property<string>("WellName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("JobUsers");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("EndDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("EndTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EntityCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("StartDepth")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("StartTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Type");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Build")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("DoglegSeverity")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<double>("SubSea")
                        .HasColumnType("float");

                    b.Property<double>("Turn")
                        .HasColumnType("float");

                    b.Property<double>("VerticalDepth")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId", "Depth");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Azimuth")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<double>("SubSeaReference")
                        .HasColumnType("float");

                    b.Property<double>("VerticalReference")
                        .HasColumnType("float");

                    b.Property<double>("VerticalSectionDirection")
                        .HasColumnType("float");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("TieOns");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wells");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.JobUser", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Runs.Run", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Jobs.Job", "Job")
                        .WithMany("Runs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Survey", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("Surveys")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.TieOn", b =>
                {
                    b.HasOne("SDI.Enki.Core.TenantDb.Wells.Well", "Well")
                        .WithMany("TieOns")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Jobs.Job", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SDI.Enki.Core.TenantDb.Wells.Well", b =>
                {
                    b.Navigation("Surveys");

                    b.Navigation("TieOns");
                });
#pragma warning restore 612, 618
        }
    }
}
