using System.Security.Cryptography;
using System.Text;
using AMR.Core.Licensing.Application;
using AMR.Core.Licensing.Infrastructure;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using SDI.Enki.Core.Master.Tools;
using SDI.Enki.Core.Master.Tools.Enums;
using SDI.Enki.Infrastructure.Licensing;
using SDI.Enki.Shared.Licensing;

namespace SDI.Enki.Infrastructure.Tests.Licensing;

/// <summary>
/// Byte-compat round-trip — Enki's <see cref="HeimdallLicenseFileGenerator"/>
/// emits envelopes that Marduk's <c>HeimdallEnvelopeDecryptor</c> +
/// <c>LicenseDocumentParser</c> accept. If this ever fails, field-deployed
/// Marduk decoders will reject .lic files generated by Enki, which means
/// nothing customer-facing should be issued from a build that doesn't
/// pass these.
///
/// Each test generates a fresh in-memory RSA keypair, writes the private
/// key to a temp file (the generator reads PEM from disk), runs Generate,
/// then decrypts + parses with Marduk's read-side classes. The temp file
/// is cleaned up in the disposable fixture.
/// </summary>
public sealed class HeimdallLicenseFileGeneratorTests : IDisposable
{
    private readonly string _tempKeyPath;
    private readonly string _publicKeyPem;
    private readonly HeimdallLicenseFileGenerator _generator;

    public HeimdallLicenseFileGeneratorTests()
    {
        _tempKeyPath = Path.Combine(Path.GetTempPath(), $"enki-licensing-test-{Guid.NewGuid():N}.pem");

        // Generate a keypair, persist the private side for the generator to
        // sign with, capture the public side in PEM for Marduk's verifier
        // to RSA-check the round-tripped signature.
        using var rsa = RSA.Create(2048);
        File.WriteAllText(_tempKeyPath, rsa.ExportRSAPrivateKeyPem(), Encoding.UTF8);
        _publicKeyPem = rsa.ExportSubjectPublicKeyInfoPem();

        var options = Options.Create(new LicensingOptions
        {
            PrivateKeyPath   = _tempKeyPath,
            Pbkdf2Iterations = 600_000,
        });

        _generator = new HeimdallLicenseFileGenerator(
            options,
            NullLogger<HeimdallLicenseFileGenerator>.Instance);
    }

    public void Dispose()
    {
        try { File.Delete(_tempKeyPath); } catch { /* best effort */ }
    }

    [Fact]
    public void Generate_emits_envelope_that_marduk_can_decrypt_and_parse()
    {
        // ---- arrange
        var licenseKey = Guid.NewGuid();
        var expiry = DateTime.UtcNow.AddYears(1).Date;
        var tool = SampleTool();
        var cal = SampleCalibration(tool.Id, tool.SerialNumber);
        var features = new LicenseFeaturesDto(
            AllowWarrior:        true,
            AllowGradient:       true,
            AllowSurvey:         true,
            AllowResults:        true,
            AllowWarriorLogging: true);

        // ---- act
        var envelope = _generator.Generate(
            licensee:             "Acme Drilling",
            licenseKey:           licenseKey,
            expiry:               expiry,
            tools:                [tool],
            calibrationsByToolId: new Dictionary<Guid, Calibration> { [tool.Id] = cal },
            features:             features);

        var decryptor = new HeimdallEnvelopeDecryptor();
        var json = decryptor.Decrypt(envelope, licenseKey.ToString("D"));
        var doc = LicenseDocumentParser.Parse(json);

        // ---- assert signature actually verifies against the public key.
        // RsaSha256SignatureVerifier reconstructs the unsigned-payload
        // canonical form from the original JSON, then RSA.VerifyData with
        // SHA256 + PKCS#1 v1.5. If the generator botched the sign step
        // (wrong padding, wrong hash, wrong key, drifted JSON shape) this
        // throws and the test fails — that's the actual contract test.
        var verifier = new RsaSha256SignatureVerifier(_publicKeyPem);
        verifier.Verify(doc, Encoding.UTF8.GetBytes(json));   // throws on bad sig

        // ---- assert envelope shape
        Assert.True(envelope.Length > 64, "Envelope should at least contain the header + nonce + tag + a real payload.");
        Assert.Equal((byte)'H', envelope[0]);
        Assert.Equal((byte)'M', envelope[1]);
        Assert.Equal((byte)'D', envelope[2]);
        Assert.Equal((byte)'L', envelope[3]);
        Assert.Equal((byte)2, envelope[4]);

        // ---- assert metadata round-trips
        Assert.Equal("Acme Drilling", doc.Payload.Licensee);
        Assert.Single(doc.Payload.Tools);
        Assert.Equal(tool.SerialNumber, doc.Payload.Tools[0].SerialNumber);
        Assert.Single(doc.Payload.Calibrations);
        Assert.Equal("BakedInCal", doc.Payload.Calibrations[0].Name);

        // ---- assert feature flags round-trip
        Assert.True(doc.Payload.AllowWarrior);
        Assert.True(doc.Payload.AllowGradient);
        Assert.True(doc.Payload.AllowSurvey);
        Assert.True(doc.Payload.AllowResults);
        Assert.True(doc.Payload.AllowWarriorLogging);
        Assert.False(doc.Payload.AllowSerial);
        Assert.False(doc.Payload.AllowGyro);

        // ---- assert signature is present + verifies against the public key
        Assert.False(string.IsNullOrWhiteSpace(doc.SignatureBase64),
            "LicenseDocumentParser must surface a non-empty Signature.");
    }

    [Fact]
    public void Generate_with_wrong_key_fails_to_decrypt()
    {
        var realKey  = Guid.NewGuid();
        var wrongKey = Guid.NewGuid();
        var tool = SampleTool();
        var cal = SampleCalibration(tool.Id, tool.SerialNumber);

        var envelope = _generator.Generate(
            "Acme Drilling", realKey, DateTime.UtcNow.AddYears(1),
            [tool],
            new Dictionary<Guid, Calibration> { [tool.Id] = cal },
            new LicenseFeaturesDto(AllowWarrior: true));

        var decryptor = new HeimdallEnvelopeDecryptor();
        Assert.Throws<CryptographicException>(() =>
            decryptor.Decrypt(envelope, wrongKey.ToString("D")));
    }

    [Fact]
    public void Signature_does_not_verify_with_a_different_public_key()
    {
        var licenseKey = Guid.NewGuid();
        var tool = SampleTool();
        var cal = SampleCalibration(tool.Id, tool.SerialNumber);

        var envelope = _generator.Generate(
            "Acme Drilling", licenseKey, DateTime.UtcNow.AddYears(1),
            [tool],
            new Dictionary<Guid, Calibration> { [tool.Id] = cal },
            new LicenseFeaturesDto(AllowWarrior: true));

        var decryptor = new HeimdallEnvelopeDecryptor();
        var json = decryptor.Decrypt(envelope, licenseKey.ToString("D"));
        var doc = LicenseDocumentParser.Parse(json);

        // Imposter keypair — signature was made with the test's private key,
        // so verifying with this stranger's public key must fail. Pins the
        // signature genuinely to the issuing keypair, not just "any bytes
        // that happen to be the right length".
        using var imposter = RSA.Create(2048);
        var imposterPubPem = imposter.ExportSubjectPublicKeyInfoPem();
        var verifier = new RsaSha256SignatureVerifier(imposterPubPem);

        Assert.Throws<CryptographicException>(() =>
            verifier.Verify(doc, Encoding.UTF8.GetBytes(json)));
    }

    [Fact]
    public void Generate_throws_when_no_tools_supplied()
    {
        Assert.Throws<ArgumentException>(() => _generator.Generate(
            "Acme Drilling", Guid.NewGuid(), DateTime.UtcNow.AddYears(1),
            tools:                Array.Empty<Tool>(),
            calibrationsByToolId: new Dictionary<Guid, Calibration>(),
            features:             new LicenseFeaturesDto()));
    }

    [Fact]
    public void Generate_throws_when_a_selected_tool_has_no_calibration()
    {
        var tool = SampleTool();

        Assert.Throws<InvalidOperationException>(() => _generator.Generate(
            "Acme Drilling", Guid.NewGuid(), DateTime.UtcNow.AddYears(1),
            tools:                [tool],
            calibrationsByToolId: new Dictionary<Guid, Calibration>(), // empty — tool has no cal
            features:             new LicenseFeaturesDto()));
    }

    /// <summary>
    /// Contract test against Marduk's <em>hardcoded</em> production public
    /// key, using the actual repo dev keypair. Field decoders (Esagila,
    /// any other Marduk consumer) verify against
    /// <c>PublicKeyPem.Value</c>; if Enki's dev <c>private.pem</c> drifts
    /// off that pair, every Enki-issued .lic will silently fail signature
    /// verification on the consumer side. This test pins the dev keypair
    /// to the public key Marduk ships with.
    ///
    /// If this fails, do NOT regenerate dev-keys. Either restore the
    /// matching keypair (see <c>dev-keys/README.md</c>) or coordinate a
    /// real key rotation across Marduk + every field decoder.
    /// </summary>
    [Fact]
    public void Generated_envelope_verifies_against_marduk_production_public_key()
    {
        var devKeyPath = ResolveDevPrivateKeyPath();
        var generator = new HeimdallLicenseFileGenerator(
            Options.Create(new LicensingOptions
            {
                PrivateKeyPath   = devKeyPath,
                Pbkdf2Iterations = 600_000,
            }),
            NullLogger<HeimdallLicenseFileGenerator>.Instance);

        var licenseKey = Guid.NewGuid();
        var tool = SampleTool();
        var cal  = SampleCalibration(tool.Id, tool.SerialNumber);

        var envelope = generator.Generate(
            "Acme Drilling", licenseKey, DateTime.UtcNow.AddYears(1),
            [tool],
            new Dictionary<Guid, Calibration> { [tool.Id] = cal },
            new LicenseFeaturesDto(AllowWarrior: true, AllowGradient: true));

        var json = new HeimdallEnvelopeDecryptor().Decrypt(envelope, licenseKey.ToString("D"));
        var doc  = LicenseDocumentParser.Parse(json);

        // The whole point — verify against Marduk's hardcoded public key, not
        // a test-generated one. RsaSha256SignatureVerifier throws on any
        // mismatch, so passing here means the dev keypair is genuinely paired
        // with PublicKeyPem.Value.
        var verifier = new RsaSha256SignatureVerifier(PublicKeyPem.Value);
        verifier.Verify(doc, Encoding.UTF8.GetBytes(json));
    }

    /// <summary>
    /// Walk up from the test assembly's bin directory until we find the
    /// repo root (marked by <c>dev-keys/private.pem</c>). Avoids hard-
    /// coding a build-output-relative path that breaks if the test
    /// framework changes its layout.
    /// </summary>
    private static string ResolveDevPrivateKeyPath()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName, "dev-keys", "private.pem");
            if (File.Exists(candidate)) return candidate;
            dir = dir.Parent;
        }
        throw new FileNotFoundException(
            "Could not locate dev-keys/private.pem by walking up from " +
            AppContext.BaseDirectory + ". Run the test from inside the Enki repo.");
    }

    // ====================== sample data ======================

    private static Tool SampleTool() => new(
        serialNumber:       1000999,
        firmwareVersion:    "1.55",
        magnetometerCount:  3,
        accelerometerCount: 1)
    {
        Id            = Guid.Parse("11111111-1111-1111-1111-111111111111"),
        Configuration = 2,
        Size          = 54000,
        Generation    = ToolGeneration.G2,
    };

    /// <summary>
    /// Hand-rolled minimal Marduk-shape ToolCalibration JSON. Uses identity
    /// permutation matrices, zero biases, unit scale factors. The exact
    /// numeric coefficients don't matter for the round-trip test — what
    /// matters is the shape so Marduk's typed deserialiser can read it.
    /// </summary>
    private static Calibration SampleCalibration(Guid toolId, int serial)
    {
        var calId = Guid.Parse("22222222-2222-2222-2222-222222222222");
        var payload = $$"""
        {
          "id": "{{calId}}",
          "toolId": "{{toolId}}",
          "name": "BakedInCal",
          "magnetometerCount": 3,
          "calibrationDate": "2026-04-29T00:00:00Z",
          "calibratedBy": "test",
          "accelerometerAxisPermutation": [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],
          "accelerometerBias": [0.0, 0.0, 0.0],
          "accelerometerScaleFactor": [1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
          "accelerometerAlignmentAngles": [0.0, 0.0, 0.0],
          "magnetometerAxisPermutation": [
            [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],
            [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],
            [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]
          ],
          "magnetometerBias": [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0],
          "magnetometerScaleFactor": [
            1.0, 1.0, 1.0, 0.0, 0.0, 0.0,
            1.0, 1.0, 1.0, 0.0, 0.0, 0.0,
            1.0, 1.0, 1.0, 0.0, 0.0, 0.0
          ],
          "magnetometerAlignmentAngles": [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0],
          "magnetometerLocations": [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0]
        }
        """;

        return new Calibration(
            toolId:          toolId,
            serialNumber:    serial,
            calibrationDate: DateTimeOffset.UtcNow,
            payloadJson:     payload)
        {
            Id                = calId,
            CalibratedBy      = "test",
            MagnetometerCount = 3,
        };
    }
}
