using System.Security.Cryptography;
using System.Text;
using AMR.Core.Licensing.Application;
using AMR.Core.Licensing.Infrastructure;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using SDI.Enki.Core.Master.Tools;
using SDI.Enki.Core.Master.Tools.Enums;
using SDI.Enki.Infrastructure.Licensing;
using SDI.Enki.Shared.Licensing;

namespace SDI.Enki.Infrastructure.Tests.Licensing;

/// <summary>
/// Byte-compat round-trip — Enki's <see cref="HeimdallLicenseFileGenerator"/>
/// emits envelopes that Marduk's <c>HeimdallEnvelopeDecryptor</c> +
/// <c>LicenseDocumentParser</c> accept. If this ever fails, field-deployed
/// Marduk decoders will reject .lic files generated by Enki, which means
/// nothing customer-facing should be issued from a build that doesn't
/// pass these.
///
/// Each test generates a fresh in-memory RSA keypair, writes the private
/// key to a temp file (the generator reads PEM from disk), runs Generate,
/// then decrypts + parses with Marduk's read-side classes. The temp file
/// is cleaned up in the disposable fixture.
/// </summary>
public sealed class HeimdallLicenseFileGeneratorTests : IDisposable
{
    private readonly string _tempKeyPath;
    private readonly HeimdallLicenseFileGenerator _generator;

    public HeimdallLicenseFileGeneratorTests()
    {
        _tempKeyPath = Path.Combine(Path.GetTempPath(), $"enki-licensing-test-{Guid.NewGuid():N}.pem");

        using var rsa = RSA.Create(2048);
        File.WriteAllText(_tempKeyPath, rsa.ExportRSAPrivateKeyPem(), Encoding.UTF8);

        var options = Options.Create(new LicensingOptions
        {
            PrivateKeyPath   = _tempKeyPath,
            Pbkdf2Iterations = 600_000,
        });

        _generator = new HeimdallLicenseFileGenerator(
            options,
            NullLogger<HeimdallLicenseFileGenerator>.Instance);
    }

    public void Dispose()
    {
        try { File.Delete(_tempKeyPath); } catch { /* best effort */ }
    }

    [Fact]
    public void Generate_emits_envelope_that_marduk_can_decrypt_and_parse()
    {
        // ---- arrange
        var licenseKey = Guid.NewGuid();
        var expiry = DateTime.UtcNow.AddYears(1).Date;
        var tool = SampleTool();
        var cal = SampleCalibration(tool.Id, tool.SerialNumber);
        var features = new LicenseFeaturesDto(
            AllowWarrior:        true,
            AllowGradient:       true,
            AllowSurvey:         true,
            AllowResults:        true,
            AllowWarriorLogging: true);

        // ---- act
        var envelope = _generator.Generate(
            licensee:             "Acme Drilling",
            licenseKey:           licenseKey,
            expiry:               expiry,
            tools:                [tool],
            calibrationsByToolId: new Dictionary<Guid, Calibration> { [tool.Id] = cal },
            features:             features);

        var decryptor = new HeimdallEnvelopeDecryptor();
        var json = decryptor.Decrypt(envelope, licenseKey.ToString("D"));
        var doc = LicenseDocumentParser.Parse(json);

        // ---- assert envelope shape
        Assert.True(envelope.Length > 64, "Envelope should at least contain the header + nonce + tag + a real payload.");
        Assert.Equal((byte)'H', envelope[0]);
        Assert.Equal((byte)'M', envelope[1]);
        Assert.Equal((byte)'D', envelope[2]);
        Assert.Equal((byte)'L', envelope[3]);
        Assert.Equal((byte)2, envelope[4]);

        // ---- assert metadata round-trips
        Assert.Equal("Acme Drilling", doc.Payload.Licensee);
        Assert.Single(doc.Payload.Tools);
        Assert.Equal(tool.SerialNumber, doc.Payload.Tools[0].SerialNumber);
        Assert.Single(doc.Payload.Calibrations);
        Assert.Equal("BakedInCal", doc.Payload.Calibrations[0].Name);

        // ---- assert feature flags round-trip
        Assert.True(doc.Payload.AllowWarrior);
        Assert.True(doc.Payload.AllowGradient);
        Assert.True(doc.Payload.AllowSurvey);
        Assert.True(doc.Payload.AllowResults);
        Assert.True(doc.Payload.AllowWarriorLogging);
        Assert.False(doc.Payload.AllowSerial);
        Assert.False(doc.Payload.AllowGyro);

        // ---- assert signature is present + verifies against the public key
        Assert.False(string.IsNullOrWhiteSpace(doc.SignatureBase64),
            "LicenseDocumentParser must surface a non-empty Signature.");
    }

    [Fact]
    public void Generate_with_wrong_key_fails_to_decrypt()
    {
        var realKey  = Guid.NewGuid();
        var wrongKey = Guid.NewGuid();
        var tool = SampleTool();
        var cal = SampleCalibration(tool.Id, tool.SerialNumber);

        var envelope = _generator.Generate(
            "Acme Drilling", realKey, DateTime.UtcNow.AddYears(1),
            [tool],
            new Dictionary<Guid, Calibration> { [tool.Id] = cal },
            new LicenseFeaturesDto(AllowWarrior: true));

        var decryptor = new HeimdallEnvelopeDecryptor();
        Assert.Throws<CryptographicException>(() =>
            decryptor.Decrypt(envelope, wrongKey.ToString("D")));
    }

    [Fact]
    public void Generate_throws_when_no_tools_supplied()
    {
        Assert.Throws<ArgumentException>(() => _generator.Generate(
            "Acme Drilling", Guid.NewGuid(), DateTime.UtcNow.AddYears(1),
            tools:                Array.Empty<Tool>(),
            calibrationsByToolId: new Dictionary<Guid, Calibration>(),
            features:             new LicenseFeaturesDto()));
    }

    [Fact]
    public void Generate_throws_when_a_selected_tool_has_no_calibration()
    {
        var tool = SampleTool();

        Assert.Throws<InvalidOperationException>(() => _generator.Generate(
            "Acme Drilling", Guid.NewGuid(), DateTime.UtcNow.AddYears(1),
            tools:                [tool],
            calibrationsByToolId: new Dictionary<Guid, Calibration>(), // empty — tool has no cal
            features:             new LicenseFeaturesDto()));
    }

    // ====================== sample data ======================

    private static Tool SampleTool() => new(
        serialNumber:       1000999,
        firmwareVersion:    "1.55",
        magnetometerCount:  3,
        accelerometerCount: 1)
    {
        Id            = Guid.Parse("11111111-1111-1111-1111-111111111111"),
        Configuration = 2,
        Size          = 54000,
        Generation    = ToolGeneration.G2,
    };

    /// <summary>
    /// Hand-rolled minimal Marduk-shape ToolCalibration JSON. Uses identity
    /// permutation matrices, zero biases, unit scale factors. The exact
    /// numeric coefficients don't matter for the round-trip test — what
    /// matters is the shape so Marduk's typed deserialiser can read it.
    /// </summary>
    private static Calibration SampleCalibration(Guid toolId, int serial)
    {
        var calId = Guid.Parse("22222222-2222-2222-2222-222222222222");
        var payload = $$"""
        {
          "id": "{{calId}}",
          "toolId": "{{toolId}}",
          "name": "BakedInCal",
          "magnetometerCount": 3,
          "calibrationDate": "2026-04-29T00:00:00Z",
          "calibratedBy": "test",
          "accelerometerAxisPermutation": [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],
          "accelerometerBias": [0.0, 0.0, 0.0],
          "accelerometerScaleFactor": [1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
          "accelerometerAlignmentAngles": [0.0, 0.0, 0.0],
          "magnetometerAxisPermutation": [
            [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],
            [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],
            [[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]
          ],
          "magnetometerBias": [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0],
          "magnetometerScaleFactor": [
            1.0, 1.0, 1.0, 0.0, 0.0, 0.0,
            1.0, 1.0, 1.0, 0.0, 0.0, 0.0,
            1.0, 1.0, 1.0, 0.0, 0.0, 0.0
          ],
          "magnetometerAlignmentAngles": [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0],
          "magnetometerLocations": [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0]
        }
        """;

        return new Calibration(
            toolId:          toolId,
            serialNumber:    serial,
            calibrationDate: DateTimeOffset.UtcNow,
            payloadJson:     payload)
        {
            Id                = calId,
            CalibratedBy      = "test",
            MagnetometerCount = 3,
        };
    }
}
