using SDI.Enki.Core.Abstractions;
using SDI.Enki.Core.TenantDb.Comments;
using SDI.Enki.Core.TenantDb.Runs;

namespace SDI.Enki.Core.TenantDb.Shots;

/// <summary>
/// One captured shot event under a Run. Single unified record type
/// — the legacy parallel <c>GradientShots</c> and <c>RotaryShots</c>
/// tables were already collapsed into a single <c>Shot</c> in the
/// pre-Phase-2 schema; Phase 2's reshape goes further and replaces
/// the 16 structured per-sample columns + the GyroShot / ToolSurvey /
/// ActiveField children with two sets of (binary file + JSON config +
/// JSON result):
///
/// <list type="bullet">
///   <item><b>Primary set</b> (<see cref="Binary"/>, <see cref="ConfigJson"/>,
///   <see cref="ResultJson"/>) — the rotary or gradient capture. Marduk
///   consumes (Binary, Config, Calibration) at calc time and produces
///   the Result.</item>
///   <item><b>Gyro set</b> (<see cref="GyroBinary"/>,
///   <see cref="GyroConfigJson"/>, <see cref="GyroResultJson"/>) —
///   optional companion gyro capture. Generated by the same downhole
///   process as the primary; only meaningful when GyroBinary is
///   present. Tiny (≤10 KB) compared to the primary.</item>
/// </list>
///
/// <para>
/// Shot belongs to exactly one Run via <see cref="RunId"/>. The legacy
/// "Gradient OR Rotary parent" CHECK constraint is gone — Run.Type is
/// authoritative for whether the Shot's Binary is rotary-shaped or
/// gradient-shaped, and Marduk uses Config to drive the calc.
/// </para>
///
/// <para>
/// Implements <see cref="IAuditable"/> + carries an EF concurrency
/// token via <c>RowVersion</c>. Soft-delete is on the parent Run, not
/// per-Shot.
/// </para>
///
/// <para>
/// <b>Future calc seam:</b> any upload of <see cref="Binary"/> or
/// change to <see cref="ConfigJson"/> sets <see cref="ResultStatus"/>
/// to <c>Pending</c> and clears the Result fields. Same pattern on
/// the Gyro side. A future calc service reads
/// <c>WHERE ResultStatus = 'Pending'</c> and processes pending Shots
/// through Marduk.
/// </para>
/// </summary>
public class Shot : IAuditable
{
    public int Id { get; set; }

    /// <summary>Parent Run. Required (Shots only exist under a Run).</summary>
    public Guid RunId { get; set; }

    /// <summary>
    /// Operator-friendly shot identifier (e.g. "shot-3A"). Indexed
    /// for fast lookup within a Run.
    /// </summary>
    public string ShotName { get; set; } = string.Empty;

    /// <summary>When the capture was taken downhole (the field-clock).</summary>
    public DateTimeOffset FileTime { get; set; }

    /// <summary>
    /// Optional FK to <see cref="Calibration"/>. Required for Marduk
    /// to compute a Result; nullable so a Shot can be uploaded
    /// before its calibration is selected. The future calc trigger
    /// gates on (Binary IS NOT NULL AND CalibrationId IS NOT NULL).
    /// </summary>
    public int? CalibrationId { get; set; }

    // ---------- primary capture set ----------

    public byte[]? Binary { get; set; }
    public string? BinaryName { get; set; }
    public DateTimeOffset? BinaryUploadedAt { get; set; }

    public string? ConfigJson { get; set; }
    public DateTimeOffset? ConfigUpdatedAt { get; set; }

    public string? ResultJson { get; set; }
    public DateTimeOffset? ResultComputedAt { get; set; }
    public string? ResultMardukVersion { get; set; }

    /// <summary>
    /// Pending / Computing / Success / Failed; <c>null</c> means
    /// idle (no calc requested yet — i.e., Binary or Config hasn't
    /// been uploaded).
    /// </summary>
    public string? ResultStatus { get; set; }
    public string? ResultError { get; set; }

    // ---------- gyro capture set ----------

    public byte[]? GyroBinary { get; set; }
    public string? GyroBinaryName { get; set; }
    public DateTimeOffset? GyroBinaryUploadedAt { get; set; }

    public string? GyroConfigJson { get; set; }
    public DateTimeOffset? GyroConfigUpdatedAt { get; set; }

    public string? GyroResultJson { get; set; }
    public DateTimeOffset? GyroResultComputedAt { get; set; }
    public string? GyroResultMardukVersion { get; set; }

    public string? GyroResultStatus { get; set; }
    public string? GyroResultError { get; set; }

    // IAuditable — managed by TenantDbContext.SaveChangesAsync.
    public DateTimeOffset   CreatedAt  { get; set; } = DateTimeOffset.UtcNow;
    public string?          CreatedBy  { get; set; }
    public DateTimeOffset?  UpdatedAt  { get; set; }
    public string?          UpdatedBy  { get; set; }
    public byte[]?          RowVersion { get; set; }

    // EF navs
    public Run? Run { get; set; }
    public Calibration? Calibration { get; set; }

    /// <summary>
    /// Comments attached to this Shot. 1:N — was m:n with Gradient /
    /// Rotary / Passive in the legacy shape; Phase 2 collapses to a
    /// single parent (Shot) since comments are about specific
    /// captures, not run-grouping abstractions.
    /// </summary>
    public ICollection<Comment> Comments { get; set; } = new List<Comment>();
}
