// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDI.Enki.Infrastructure.Data;

#nullable disable

namespace SDI.Enki.Infrastructure.Migrations.Master
{
    [DbContext(typeof(AthenaMasterDbContext))]
    [Migration("20260424194800_AddTenantAuditFields")]
    partial class AddTenantAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDI.Enki.Core.Master.Migrations.MigrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("MigrationRun");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Settings.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonObject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tenants.TenantDatabase", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastBackupAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastMigrationAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ServerInstance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "Kind");

                    b.ToTable("TenantDatabase");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUser");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tools.Calibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalibratedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CalibrationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("ToolId");

                    b.ToTable("Calibration");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tools.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccelerometerCount")
                        .HasColumnType("int");

                    b.Property<int>("Configuration")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MagnetometerCount")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Tool");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a519cae-da73-41df-82dd-05fbc8bc73a0"),
                            IdentityId = new Guid("8cf4b730-c619-49d0-8ed7-be0ac89de718"),
                            Name = "dapo.ajayi"
                        },
                        new
                        {
                            Id = new Guid("e8dd0c2a-bceb-4885-a90e-8f9cf446ee5a"),
                            IdentityId = new Guid("f8aff5b3-473b-436f-9592-186cb28ac848"),
                            Name = "jamie.dorey"
                        },
                        new
                        {
                            Id = new Guid("ab3f526a-849b-492b-91d9-f3851e978869"),
                            IdentityId = new Guid("dafd065f-4790-4235-9db0-6f47abadf3aa"),
                            Name = "adam.karabasz"
                        },
                        new
                        {
                            Id = new Guid("02c9751a-3058-4e15-b5c5-ce82adaebaeb"),
                            IdentityId = new Guid("bd34385d-2d88-4781-bef5-e955ddaa8293"),
                            Name = "douglas.ridgway"
                        },
                        new
                        {
                            Id = new Guid("123505bf-cd91-4e15-b583-ad1291347508"),
                            IdentityId = new Guid("e5a7f984-688a-4904-8155-3fe724584385"),
                            Name = "travis.solomon"
                        },
                        new
                        {
                            Id = new Guid("f5fd1207-1dc6-49c7-a794-b5420bd88008"),
                            IdentityId = new Guid("1e333b45-1448-4b26-a68d-b4effbbdcd9d"),
                            Name = "mike.king"
                        },
                        new
                        {
                            Id = new Guid("ce17bb43-1eac-439e-80a5-324a3edaf373"),
                            IdentityId = new Guid("a72f07d8-9a12-4825-95f4-7c5bbea6e6e5"),
                            Name = "james.powell"
                        },
                        new
                        {
                            Id = new Guid("e48bacc4-4375-4445-88b0-e08c20216513"),
                            IdentityId = new Guid("f8d3ceda-ce98-4825-88f9-c8e8356a61db"),
                            Name = "joel.harrison"
                        },
                        new
                        {
                            Id = new Guid("050add37-54b3-4996-9bcc-8ed3cc4992b6"),
                            IdentityId = new Guid("bc120086-fc2d-4f41-b76a-3f6c3536c2cc"),
                            Name = "scott.brandel"
                        },
                        new
                        {
                            Id = new Guid("0c2c609c-abb0-4009-8928-e274352caf11"),
                            IdentityId = new Guid("d92be0d5-dfbe-4d1d-9823-1ca37617dade"),
                            Name = "john.borders"
                        },
                        new
                        {
                            Id = new Guid("f9830a6a-d787-4333-9e66-aa03c9a58b51"),
                            IdentityId = new Guid("92473a14-0196-42ed-b098-9c3d85505f8d"),
                            Name = "karl.king"
                        },
                        new
                        {
                            Id = new Guid("466ba5fd-d339-4a92-93bc-ec3354a98945"),
                            IdentityId = new Guid("2c4f110e-adc4-4759-aa34-b73ec0954c9e"),
                            Name = "gavin.helboe"
                        });
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Users.UserTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserTemplate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default security template; contains access for all team members.",
                            Name = "All Team Access"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Technical security template; contains access for technical team members.",
                            Name = "Technical Team Access"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Senior security template; contains access for senior team members.",
                            Name = "Senior Team Access"
                        });
                });

            modelBuilder.Entity("SettingUser", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SettingId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("SettingUser", (string)null);
                });

            modelBuilder.Entity("UserUserTemplate", b =>
                {
                    b.Property<int>("TemplatesId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplatesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserUserTemplate", (string)null);

                    b.HasData(
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("7a519cae-da73-41df-82dd-05fbc8bc73a0")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("e8dd0c2a-bceb-4885-a90e-8f9cf446ee5a")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("ab3f526a-849b-492b-91d9-f3851e978869")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("02c9751a-3058-4e15-b5c5-ce82adaebaeb")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("123505bf-cd91-4e15-b583-ad1291347508")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("f5fd1207-1dc6-49c7-a794-b5420bd88008")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("ce17bb43-1eac-439e-80a5-324a3edaf373")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("e48bacc4-4375-4445-88b0-e08c20216513")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("050add37-54b3-4996-9bcc-8ed3cc4992b6")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("0c2c609c-abb0-4009-8928-e274352caf11")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("f9830a6a-d787-4333-9e66-aa03c9a58b51")
                        },
                        new
                        {
                            TemplatesId = 1,
                            UsersId = new Guid("466ba5fd-d339-4a92-93bc-ec3354a98945")
                        },
                        new
                        {
                            TemplatesId = 2,
                            UsersId = new Guid("f5fd1207-1dc6-49c7-a794-b5420bd88008")
                        },
                        new
                        {
                            TemplatesId = 2,
                            UsersId = new Guid("02c9751a-3058-4e15-b5c5-ce82adaebaeb")
                        },
                        new
                        {
                            TemplatesId = 2,
                            UsersId = new Guid("f9830a6a-d787-4333-9e66-aa03c9a58b51")
                        },
                        new
                        {
                            TemplatesId = 2,
                            UsersId = new Guid("466ba5fd-d339-4a92-93bc-ec3354a98945")
                        },
                        new
                        {
                            TemplatesId = 3,
                            UsersId = new Guid("e8dd0c2a-bceb-4885-a90e-8f9cf446ee5a")
                        },
                        new
                        {
                            TemplatesId = 3,
                            UsersId = new Guid("e48bacc4-4375-4445-88b0-e08c20216513")
                        });
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tenants.TenantDatabase", b =>
                {
                    b.HasOne("SDI.Enki.Core.Master.Tenants.Tenant", "Tenant")
                        .WithMany("Databases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tenants.TenantUser", b =>
                {
                    b.HasOne("SDI.Enki.Core.Master.Tenants.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.Master.Users.User", "User")
                        .WithMany("Tenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tools.Calibration", b =>
                {
                    b.HasOne("SDI.Enki.Core.Master.Tools.Tool", "Tool")
                        .WithMany("Calibrations")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("SettingUser", b =>
                {
                    b.HasOne("SDI.Enki.Core.Master.Settings.Setting", null)
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.Master.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserTemplate", b =>
                {
                    b.HasOne("SDI.Enki.Core.Master.Users.UserTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDI.Enki.Core.Master.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tenants.Tenant", b =>
                {
                    b.Navigation("Databases");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Tools.Tool", b =>
                {
                    b.Navigation("Calibrations");
                });

            modelBuilder.Entity("SDI.Enki.Core.Master.Users.User", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
